=== KreoSan14/ratgore-kreosan-shit/Schemas/rsi.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "default": {},
    "description": "JSON Schema for SS14 RSI validation.",
    "examples": [
        {
            "version": 1,
            "license": "CC-BY-SA-3.0",
            "copyright": "Taken from CODEBASE at COMMIT PERMALINK",
            "size": {
                "x": 32,
                "y": 32
            },
            "states": [
                {
                    "name": "basic"
                },
                {
                    "name": "basic-directions",
                    "directions": 4
                },
                {
                    "name": "basic-delays",
                    "delays": [
                        [
                            0.1,
                            0.1
                        ]
                    ]
                },
                {
                    "name": "basic-delays-directions",
                    "directions": 4,
                    "delays": [
                        [
                            0.1,
                            0.1
                        ],
                        [
                            0.1,
                            0.1
                        ],
                        [
                            0.1,
                            0.1
                        ],
                        [
                            0.1,
                            0.1
                        ]
                    ]
                }
            ]
        }
    ],
    "required": [
        "version",
        "license",
        "copyright",
        "size",
        "states"
    ],
    "title": "RSI Schema",
    "type": "object",
    "properties": {
        "version": {
            "$id": "#/properties/version",
            "default": "",
            "description": "RSI version integer.",
            "title": "The version schema",
            "type": "integer"
        },
        "license": {
            "$id": "#/properties/license",
            "default": "",
            "description": "The license for the associated icon states. Restricted to SS14-compatible asset licenses.",
            "examples": [
                "CC-BY-SA-3.0"
            ],
            "title": "License",
            "type": "string"
        },
        "copyright": {
            "$id": "#/properties/copyright",
            "type": "string",
            "title": "Copyright Info",
            "description": "The copyright holder. This is typically a link to the commit of the codebase that the icon is pulled from.",
            "default": "",
            "examples": [
                "Taken from CODEBASE at COMMIT LINK"
            ]
        },
        "size": {
            "$id": "#/properties/size",
            "default": {},
            "description": "The dimensions of the sprites inside the RSI.  This is not the size of the PNG files that store the sprite sheet.",
            "examples": [
                {
                    "x": 32,
                    "y": 32
                }
            ],
            "title": "Sprite Dimensions",
            "required": [
                "x",
                "y"
            ],
            "type": "object",
            "properties": {
                "x": {
                    "$id": "#/properties/size/properties/x",
                    "type": "integer",
                    "default": 32,
                    "examples": [
                        32
                    ]
                },
                "y": {
                    "$id": "#/properties/size/properties/y",
                    "type": "integer",
                    "default": 32,
                    "examples": [
                        32
                    ]
                }
            },
            "additionalProperties": true
        },
        "states": {
            "$id": "#/properties/states",
            "type": "array",
            "title": "Icon States",
            "description": "Metadata for icon states. Includes name, directions, delays, etc.",
            "default": [],
            "examples": [
                [
                    {
                        "name": "basic"
                    },
                    {
                        "name": "basic-directions",
                        "directions": 4
                    }
                ]
            ],
            "additionalItems": true,
            "items": {
                "$id": "#/properties/states/items",
                "type": "object",
                "required": [
                    "name"
                ],
                "properties": {
                    "name": {
                        "type": "string"
                    },
                    "directions": {
                        "type": "integer",
                        "enum": [
                            1,
                            4,
                            8
                        ]
                    },
                    "delays": {
                        "type": "array",
                        "items": {
                            "type": "array",
                            "items": {
                                "type": "number"
                            }
                        }
                    }
                }
            }
        }
    },
    "additionalProperties": true
}

=== KreoSan14/ratgore-kreosan-shit/Resources/Textures/_Crescent/Objects/Weapons/Ammunition/New_Ammo/Casings/.277.rsi/meta.json
{
    "version": 1,
    "size": {
        "x": 32,
        "y": 32
    },
    "license": "",
    "copyright": "sprites provided by @WillyBillyGilly, licensed under CC-BY-SA 3.0",
    "states": [
        {
            "name": "base"
        },
        {
            "name": "base-spent"
        },
        {
            "name": "tip"
        }
    ]
}

=== KreoSan14/ratgore-kreosan-shit/Resources/Textures/_Crescent/Objects/Tools/New_Tools/t-ray.rsi/meta.json
{
  "version": 1,
  "license": "CC-BY-SA-3.0",
      "copyright": "sprites provided by @WillyBillyGilly and @miket, licensed under CC-BY-SA 3.0",
	"size": { "x": 32, "y": 32 },
	"states": [
		{ "name": "t-ray-on" , "delays": [[0.5, 0.5]]},
		{ "name": "t-ray-off" },
    {
      "name": "inhand-left",
      "directions": 4
    },
    {
      "name": "inhand-right",
      "directions": 4
    }
  ]
}

=== KreoSan14/ratgore-kreosan-shit/Resources/Textures/_Crescent/Objects/Turrets/Laser/scourer.rsi/meta.json
{
    "version": 1,
    "license": "",
    "copyright": "Built by the Hullrot Team for the Hullrot Project. All rights reserved. This art is proprietary. Do not modify, redistribute, relicense, or use in any way.",
    "size": {
        "x": 64,
        "y": 64
    },
    "states": [
        {
            "name": "scourer"
        }
    ]
}

=== KreoSan14/ratgore-kreosan-shit/Resources/Textures/_Crescent/Objects/Tools/New_Tools/drill.rsi/meta.json
{
  "version": 1,
  "license": "CC-BY-SA-3.0",
  "copyright": "sprites provided by @WillyBillyGilly and @miket, licensed under CC-BY-SA 3.0",
  "size": {
    "x": 32,
    "y": 32
  },
  "states": [
    {
      "name": "drill_bolt"
    },
    {
      "name": "drill_screw"
    },
    {
      "name": "inhand-left",
      "directions": 4
    },
    {
      "name": "inhand-right",
      "directions": 4
    }
  ]
}

=== KreoSan14/ratgore-kreosan-shit/Resources/Textures/_Crescent/Objects/Weapons/Ammunition/New_Ammo/Magazine/.42_PstlMag.rsi/meta.json
{
    "version": 1,
    "size": {
        "x": 32,
        "y": 32
    },
    "license": "",
    "copyright": "sprites provided by @WillyBillyGilly, licensed under CC-BY-SA 3.0",
    "states": [
        {
            "name": "base"
        },
        {
            "name": "icon"
        },
        {
            "name": "mag-0"
        },
        {
            "name": "mag-1"
        },
        {
            "name": "mag-2"
        },
        {
            "name": "mag-3"
        },
        {
            "name": "mag-4"
        },
        {
            "name": "mag-5"
        },
        {
            "name": "mag-6"
        },
        {
            "name": "mag-7"
        }
    ]
}

=== KreoSan14/ratgore-kreosan-shit/Resources/Textures/_Crescent/Objects/Weapons/Guns/New_Guns/RIFLE/AK-74/meta.json
{
    "version": 1,
    "license": "",
    "copyright": "sprites provided by @WillyBillyGilly, licensed under CC-BY-SA 3.0",
    "size": {
        "x": 48,
        "y": 32
    },
    "states": [
        {
            "name": "icon"
        },
        {
            "name": "base"
        },
        {
            "name": "bolt-open"
        },
        {
            "name": "mag-0"
        },
        {
            "name": "inhand-left",
            "directions": 4
        },
        {
            "name": "inhand-right",
            "directions": 4
        },
        {
            "name": "wielded-inhand-left",
            "directions": 4
        },
        {
            "name": "wielded-inhand-right",
            "directions": 4
        },
        {
            "name": "equipped-BACKPACK",
            "directions": 4
        },
        {
            "name": "equipped-SUITSTORAGE",
            "directions": 4
        }
    ]
}

=== KreoSan14/ratgore-kreosan-shit/Resources/Textures/_Crescent/Objects/Weapons/Guns/harba.rsi/meta.json
{
    "version": 1,
    "license": "",
    "copyright": "Made by the Sector Crescent team for the Hullrot Project. All rights reserved. Do not modify, publish, use, relicense, or edit. Modified by soot for ratgore with approval of crescent team as per sublicense. :)",
    "size": {
        "x": 48,
        "y": 32
    },
    "states": [
        {
            "name": "icon"
        },
        {
            "name": "base"
        },
        {
            "name": "bolt-open"
        },
        {
            "name": "inhand-left",
            "directions": 4
        },
        {
            "name": "inhand-right",
            "directions": 4
        },
        {
            "name": "wielded-inhand-left",
            "directions": 4
        },
        {
            "name": "wielded-inhand-right",
            "directions": 4
        },
        {
            "name": "equipped-BACKPACK",
            "directions": 4
        },
        {
            "name": "equipped-SUITSTORAGE",
            "directions": 4
        }
    ]
}

=== KreoSan14/ratgore-kreosan-shit/Resources/Textures/_Crescent/Objects/Tools/New_Tools/blowtorch.rsi/meta.json
{
  "version": 1,
  "license": "CC-BY-SA-3.0",
  "copyright": "sprites provided by @WillyBillyGilly and @miket, licensed under CC-BY-SA 3.0",
  "size": {
    "x": 32,
    "y": 32
  },
  "states": [
    {
      "name": "icon"
    },
    {
      "name": "welder_flame",
      "delays": [
        [
          0.2,
          0.1
        ]
      ]
    },
    {
      "name": "inhand-left",
      "directions": 4
    },
    {
      "name": "inhand-right",
      "directions": 4
    },
    {
      "name": "inhand-left-flame",
      "directions": 4,
      "delays": [
        [
          0.2,
          0.2,
          0.2
        ],
        [
          0.2,
          0.2,
          0.2
        ],
        [
          0.2,
          0.2,
          0.2
        ],
        [
          0.2,
          0.2,
          0.2
        ]
      ]
    },
    {
      "name": "inhand-right-flame",
      "directions": 4,
      "delays": [
        [
          0.2,
          0.2,
          0.2
        ],
        [
          0.2,
          0.2,
          0.2
        ],
        [
          0.2,
          0.2,
          0.2
        ],
        [
          0.2,
          0.2,
          0.2
        ]
      ]
    }
  ]
}
